package com.invest.pro.application.model.master;// default package
// Generated Sep 27, 2015 7:52:02 PM by Hibernate Tools 3.4.0.CR1

import com.google.common.collect.Sets;
import com.invest.pro.application.model.internal.PrimitiveIdAbstractEntity;
import com.invest.pro.application.property.PropertiesHolder;
import com.invest.pro.application.property.info.PrimitiveDataTypePropertyInfo;
import com.invest.pro.application.property.info.PropertyInfo;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;
import java.util.Set;

/**
 * MAmc generated by hbm2java
 */
@Entity
@Table(name = "M_AMC")
public class MAmc extends PrimitiveIdAbstractEntity<Long, MAmc> {

    private static final EntityProperties properties = new EntityProperties();

    @Column(name = "AMC_CD")
	private String amcCd;

    @Column(name = "AMC_NAME")
	private String amcName;

    @Column(name = "ACTIVE")
	private Boolean active;

	public String getAmcCd() {
		return this.amcCd;
	}

	public void setAmcCd(String amcCd) {
		this.amcCd = amcCd;
	}

	public String getAmcName() {
		return this.amcName;
	}

	public void setAmcName(String amcName) {
		this.amcName = amcName;
	}

	public Boolean getActive() {
		return this.active;
	}

	public void setActive(Boolean active) {
		this.active = active;
	}


    @Override
    public PropertiesHolder<MAmc> getPropertyHolder() {
        return properties;
    }

    private static class EntityProperties implements PropertiesHolder<MAmc> {
        private static final Set<PropertyInfo> PROPERTIES_TO_MERGE = Sets.newHashSet(
                (PropertyInfo) new PrimitiveDataTypePropertyInfo<String>(String.class, "amcCd"),
                (PropertyInfo) new PrimitiveDataTypePropertyInfo<String>(String.class, "amcName")
        );

        @Override
        public Set<PropertyInfo> getPropertiesInfoToBeMerged() {
            return PROPERTIES_TO_MERGE;
        }
    }
}
