package com.invest.pro.application.model.master;// default package
// Generated Sep 27, 2015 7:52:02 PM by Hibernate Tools 3.4.0.CR1

import com.google.common.collect.Sets;
import com.invest.pro.application.model.internal.PrimitiveIdAbstractEntity;
import com.invest.pro.application.property.PropertiesHolder;
import com.invest.pro.application.property.info.PrimitiveDataTypePropertyInfo;
import com.invest.pro.application.property.info.PropertyInfo;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;
import java.util.Set;

/**
 * MBankName generated by hbm2java
 */
@Entity
@Table(name = "M_BANK_NAME")
public class MBankName extends PrimitiveIdAbstractEntity<Long, MBankName> {

    private static final EntityProperties properties = new EntityProperties();

    @Column(name = "BANK_NAME")
	private String bankName;

    @Column(name = "BANK_CD")
	private String bankCd;

    @Column(name = "ACTIVE")
	private Boolean active;


	public String getBankName() {
		return this.bankName;
	}

	public void setBankName(String bankName) {
		this.bankName = bankName;
	}

	public String getBankCd() {
		return this.bankCd;
	}

	public void setBankCd(String bankCd) {
		this.bankCd = bankCd;
	}

	public Boolean getActive() {
		return this.active;
	}

	public void setActive(Boolean active) {
		this.active = active;
	}

    @Override
    public PropertiesHolder<MBankName> getPropertyHolder() {
        return properties;
    }

    private static class EntityProperties implements PropertiesHolder<MBankName> {
        private static final Set<PropertyInfo> PROPERTIES_TO_MERGE = Sets.newHashSet(
                (PropertyInfo) new PrimitiveDataTypePropertyInfo<String>(String.class, "bankCd"),
                (PropertyInfo) new PrimitiveDataTypePropertyInfo<String>(String.class, "bankName")
        );

        @Override
        public Set<PropertyInfo> getPropertiesInfoToBeMerged() {
            return PROPERTIES_TO_MERGE;
        }
    }
}
