package com.invest.pro.application.model.master;// default package
// Generated Sep 27, 2015 7:52:02 PM by Hibernate Tools 3.4.0.CR1

import com.google.common.collect.Sets;
import com.invest.pro.application.model.internal.PrimitiveIdAbstractEntity;
import com.invest.pro.application.property.PropertiesHolder;
import com.invest.pro.application.property.info.PrimitiveDataTypePropertyInfo;
import com.invest.pro.application.property.info.PropertyInfo;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;
import java.util.Set;

/**
 * MDepositingCompany generated by hbm2java
 */
@Entity
@Table(name = "M_DEPOSITING_COMPANY")
public class MDepositingCompany extends PrimitiveIdAbstractEntity<Long, MDepositingCompany> {

    private static final EntityProperties properties = new EntityProperties();

    @Column(name = "DEPOSITE_COMPANY_CD")
	private String depositeCompanyCd;

    @Column(name = "DEPOSITE_COMPANY_NAME")
	private String depositeCompanyName;

    @Column(name = "ACTIVE")
	private Boolean active;

	public String getDepositeCompanyCd() {
		return this.depositeCompanyCd;
	}

	public void setDepositeCompanyCd(String depositeCompanyCd) {
		this.depositeCompanyCd = depositeCompanyCd;
	}

	public String getDepositeCompanyName() {
		return this.depositeCompanyName;
	}

	public void setDepositeCompanyName(String depositeCompanyName) {
		this.depositeCompanyName = depositeCompanyName;
	}

	public Boolean getActive() {
		return this.active;
	}

	public void setActive(Boolean active) {
		this.active = active;
	}

    @Override
    public PropertiesHolder<MDepositingCompany> getPropertyHolder() {
        return properties;
    }

    private static class EntityProperties implements PropertiesHolder<MDepositingCompany> {
        private static final Set<PropertyInfo> PROPERTIES_TO_MERGE = Sets.newHashSet(
                (PropertyInfo) new PrimitiveDataTypePropertyInfo<String>(String.class, "depositeCompanyCd"),
                (PropertyInfo) new PrimitiveDataTypePropertyInfo<String>(String.class, "depositeCompanyName")
        );

        @Override
        public Set<PropertyInfo> getPropertiesInfoToBeMerged() {
            return PROPERTIES_TO_MERGE;
        }
    }
}
