package com.invest.pro.application.model.master;// default package
// Generated Sep 27, 2015 7:52:02 PM by Hibernate Tools 3.4.0.CR1

import com.google.common.collect.Sets;
import com.invest.pro.application.model.internal.PrimitiveIdAbstractEntity;
import com.invest.pro.application.property.PropertiesHolder;
import com.invest.pro.application.property.info.PrimitiveDataTypePropertyInfo;
import com.invest.pro.application.property.info.PropertyInfo;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;
import java.util.Set;

/**
 * MFundName generated by hbm2java
 */
@Entity
@Table(name = "M_FUND_NAME")
public class MFundName extends PrimitiveIdAbstractEntity<Long, MFundName> {

    private static final EntityProperties properties = new EntityProperties();

    @Column(name = "FUND_CD")
	private String fundCd;

    @Column(name = "FUND_NAME")
	private String fundName;

    @Column(name = "ACTIVE")
	private Boolean active;

	public String getFundCd() {
		return this.fundCd;
	}

	public void setFundCd(String fundCd) {
		this.fundCd = fundCd;
	}

	public String getFundName() {
		return this.fundName;
	}

	public void setFundName(String fundName) {
		this.fundName = fundName;
	}

	public Boolean getActive() {
		return this.active;
	}

	public void setActive(Boolean active) {
		this.active = active;
	}


    @Override
    public PropertiesHolder<MFundName> getPropertyHolder() {
        return properties;
    }

    private static class EntityProperties implements PropertiesHolder<MFundName> {
        private static final Set<PropertyInfo> PROPERTIES_TO_MERGE = Sets.newHashSet(
                (PropertyInfo) new PrimitiveDataTypePropertyInfo<String>(String.class, "fundCd"),
                (PropertyInfo) new PrimitiveDataTypePropertyInfo<String>(String.class, "fundName")
        );

        @Override
        public Set<PropertyInfo> getPropertiesInfoToBeMerged() {
            return PROPERTIES_TO_MERGE;
        }
    }
}
