package com.invest.pro.application.model.master;// default package
// Generated Sep 27, 2015 7:52:02 PM by Hibernate Tools 3.4.0.CR1

import com.google.common.collect.Sets;
import com.invest.pro.application.model.internal.PrimitiveIdAbstractEntity;
import com.invest.pro.application.property.PropertiesHolder;
import com.invest.pro.application.property.info.PrimitiveDataTypePropertyInfo;
import com.invest.pro.application.property.info.PropertyInfo;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;
import java.util.Set;

/**
 * MInvestmentType generated by hbm2java
 */
@Entity
@Table(name = "M_INVESTMENT_TYPE")
public class MInvestmentType extends PrimitiveIdAbstractEntity<Long, MInvestmentType> {

    private static final EntityProperties properties = new EntityProperties();


    @Column(name = "INVESTMENT_CD")
	private String investmentCd;

    @Column(name = "INVESTMENT_NAME")
	private String investmentName;

    @Column(name = "ACTIVE")
	private Boolean active;


	public String getInvestmentCd() {
		return this.investmentCd;
	}

	public void setInvestmentCd(String investmentCd) {
		this.investmentCd = investmentCd;
	}

	public String getInvestmentName() {
		return this.investmentName;
	}

	public void setInvestmentName(String investmentName) {
		this.investmentName = investmentName;
	}

	public Boolean getActive() {
		return this.active;
	}

	public void setActive(Boolean active) {
		this.active = active;
	}

    @Override
    public PropertiesHolder<MInvestmentType> getPropertyHolder() {
        return properties;
    }

    private static class EntityProperties implements PropertiesHolder<MInvestmentType> {
        private static final Set<PropertyInfo> PROPERTIES_TO_MERGE = Sets.newHashSet(
                (PropertyInfo) new PrimitiveDataTypePropertyInfo<String>(String.class, "investmentCd"),
                (PropertyInfo) new PrimitiveDataTypePropertyInfo<String>(String.class, "investmentName")
        );

        @Override
        public Set<PropertyInfo> getPropertiesInfoToBeMerged() {
            return PROPERTIES_TO_MERGE;
        }
    }
}
