package com.invest.pro.application.model.master;// default package
// Generated Sep 27, 2015 7:52:02 PM by Hibernate Tools 3.4.0.CR1

import com.google.common.collect.Sets;
import com.invest.pro.application.model.internal.PrimitiveIdAbstractEntity;
import com.invest.pro.application.property.PropertiesHolder;
import com.invest.pro.application.property.info.PrimitiveDataTypePropertyInfo;
import com.invest.pro.application.property.info.PropertyInfo;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;
import java.util.Set;

/**
 * MMutualFundSubOption generated by hbm2java
 */
@Entity
@Table(name = "M_MUTUAL_FUND_SUB_OPTION")
public class MMutualFundSubOption extends PrimitiveIdAbstractEntity<Long, MMutualFundSubOption> {

    private static final EntityProperties properties = new EntityProperties();

    @Column(name = "MUTUAL_FUND_SUB_CD")
	private String mutualFundSubCd;

    @Column(name = "MUTUAL_FUND_SUB_NAME")
	private String mutualFundSubName;

    @Column(name = "ACTIVE")
	private Boolean active;

	public String getMutualFundSubCd() {
		return this.mutualFundSubCd;
	}

	public void setMutualFundSubCd(String mutualFundSubCd) {
		this.mutualFundSubCd = mutualFundSubCd;
	}

	public String getMutualFundSubName() {
		return this.mutualFundSubName;
	}

	public void setMutualFundSubName(String mutualFundSubName) {
		this.mutualFundSubName = mutualFundSubName;
	}

	public Boolean getActive() {
		return this.active;
	}

	public void setActive(Boolean active) {
		this.active = active;
	}


    @Override
    public PropertiesHolder<MMutualFundSubOption> getPropertyHolder() {
        return properties;
    }

    private static class EntityProperties implements PropertiesHolder<MMutualFundSubOption> {
        private static final Set<PropertyInfo> PROPERTIES_TO_MERGE = Sets.newHashSet(
                (PropertyInfo) new PrimitiveDataTypePropertyInfo<String>(String.class, "mutualFundSubCd"),
                (PropertyInfo) new PrimitiveDataTypePropertyInfo<String>(String.class, "mutualFundSubName")
        );

        @Override
        public Set<PropertyInfo> getPropertiesInfoToBeMerged() {
            return PROPERTIES_TO_MERGE;
        }
    }
}
