package com.invest.pro.application.model.master;// default package
// Generated Sep 27, 2015 7:52:02 PM by Hibernate Tools 3.4.0.CR1

import com.google.common.collect.Sets;
import com.invest.pro.application.model.internal.PrimitiveIdAbstractEntity;
import com.invest.pro.application.property.PropertiesHolder;
import com.invest.pro.application.property.info.PrimitiveDataTypePropertyInfo;
import com.invest.pro.application.property.info.PropertyInfo;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;
import java.util.Set;

/**
 * MMutualFundOption generated by hbm2java
 */
@Entity
@Table(name = "M_MUTUAL_FUND_OPTION")
public class MMutualFundOption extends PrimitiveIdAbstractEntity<Long, MMutualFundOption> {

    private static final EntityProperties properties = new EntityProperties();

    @Column(name = "MUTUAL_FUND_CD")
	private String mutualFundCd;

    @Column(name = "MUTUAL_FUND_NAME")
	private String mutualFundName;

    @Column(name = "ACTIVE")
	private Boolean active;

	public String getMutualFundCd() {
		return this.mutualFundCd;
	}

	public void setMutualFundCd(String mutualFundCd) {
		this.mutualFundCd = mutualFundCd;
	}

	public String getMutualFundName() {
		return this.mutualFundName;
	}

	public void setMutualFundName(String mutualFundName) {
		this.mutualFundName = mutualFundName;
	}

	public Boolean getActive() {
		return this.active;
	}

	public void setActive(Boolean active) {
		this.active = active;
	}

    @Override
    public PropertiesHolder<MMutualFundOption> getPropertyHolder() {
        return properties;
    }

    private static class EntityProperties implements PropertiesHolder<MMutualFundOption> {
        private static final Set<PropertyInfo> PROPERTIES_TO_MERGE = Sets.newHashSet(
                (PropertyInfo) new PrimitiveDataTypePropertyInfo<String>(String.class, "mutualFundCd"),
                (PropertyInfo) new PrimitiveDataTypePropertyInfo<String>(String.class, "mutualFundName")
        );

        @Override
        public Set<PropertyInfo> getPropertiesInfoToBeMerged() {
            return PROPERTIES_TO_MERGE;
        }
    }
}
