package com.invest.pro.application.model.master;// default package
// Generated Sep 27, 2015 7:52:02 PM by Hibernate Tools 3.4.0.CR1

import com.google.common.collect.Sets;
import com.invest.pro.application.model.internal.PrimitiveIdAbstractEntity;
import com.invest.pro.application.property.PropertiesHolder;
import com.invest.pro.application.property.info.PrimitiveDataTypePropertyInfo;
import com.invest.pro.application.property.info.PropertyInfo;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;
import java.util.Set;

/**
 * MPaymentMode generated by hbm2java
 */
@Entity
@Table(name = "M_PAYMENT_MODE")
public class MPaymentMode extends PrimitiveIdAbstractEntity<Long, MPaymentMode> {

    private static final EntityProperties properties = new EntityProperties();

    @Column(name = "PAYMENT_CD")
	private String paymentCd;

    @Column(name = "PAYMENT_NAME")
	private String paymentName;

    @Column(name = "ACTIVE")
	private Boolean active;

	public String getPaymentCd() {
		return this.paymentCd;
	}

	public void setPaymentCd(String paymentCd) {
		this.paymentCd = paymentCd;
	}

	public String getPaymentName() {
		return this.paymentName;
	}

	public void setPaymentName(String paymentName) {
		this.paymentName = paymentName;
	}

	public Boolean getActive() {
		return this.active;
	}

	public void setActive(Boolean active) {
		this.active = active;
	}


    @Override
    public PropertiesHolder<MPaymentMode> getPropertyHolder() {
        return properties;
    }

    private static class EntityProperties implements PropertiesHolder<MPaymentMode> {
        private static final Set<PropertyInfo> PROPERTIES_TO_MERGE = Sets.newHashSet(
                (PropertyInfo) new PrimitiveDataTypePropertyInfo<String>(String.class, "paymentCd"),
                (PropertyInfo) new PrimitiveDataTypePropertyInfo<String>(String.class, "paymentName")
        );

        @Override
        public Set<PropertyInfo> getPropertiesInfoToBeMerged() {
            return PROPERTIES_TO_MERGE;
        }
    }
}
