package com.invest.pro.application.model.transaction;// default package
// Generated Sep 27, 2015 7:52:02 PM by Hibernate Tools 3.4.0.CR1

import com.google.common.collect.Sets;
import com.invest.pro.application.model.business.BUserProfile;
import com.invest.pro.application.model.internal.PrimitiveIdAbstractEntity;
import com.invest.pro.application.model.master.MAmc;
import com.invest.pro.application.model.master.MBankName;
import com.invest.pro.application.model.master.MMutualFundOption;
import com.invest.pro.application.model.master.MMutualFundSubOption;
import com.invest.pro.application.property.PropertiesHolder;
import com.invest.pro.application.property.info.PrimitiveDataTypePropertyInfo;
import com.invest.pro.application.property.info.PropertyInfo;

import javax.persistence.*;
import java.util.Date;
import java.util.Set;

/**
 * TFixedDepositeDetail generated by hbm2java
 */
@Entity
@Table(name = "T_MUTUAL_FUND_DETAIL")
@NamedQueries(value = {
        @NamedQuery(name = "TMutualFundDetail.findByFolioNumber", query = "FROM TMutualFundDetail u where u.folioNumber = ?1")
})
public class TMutualFundDetail extends PrimitiveIdAbstractEntity<Long, TMutualFundDetail> {

    private static final EntityProperties properties = new EntityProperties();
//TODO Add JSR Validation
    @Column(name = "INVESTMENT_DATE")
	private Date investmentDate;

    @Column(name = "FOLIO_NUMBER")
	private String folioNumber;

    @Column(name = "CHEQUE_NUMBER")
	private String chequeNumber;

    @Column(name = "INVESTMENT_AMOUNT")
	private long investmentAmount;

    @Column(name = "SIP_END_YEAR")
	private String sipEndYear;

    @Column(name = "SIP_END_MONTH")
	private String sipEndMonth;

    @Column(name = "SIP_END_DATE")
	private String sipEndDate;

    @Column(name = "ACCOUNT_NUMBER")
	private String accountNumber;

    @Column(name = "MICR_NUMBER")
	private String micrNumber;

    @OneToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "INVESTOR_ID", referencedColumnName = "ID")
	private BUserProfile investorId;


    @OneToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "AMC_ID", referencedColumnName = "ID")
	private MAmc amcId;


    @OneToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "MUTUAL_FUND_OPTION_ID", referencedColumnName = "ID")
	private MMutualFundOption mutualFundOptionId;

    @OneToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "MUTUAL_FUND_SUB_OPTION_ID", referencedColumnName = "ID")
	private MMutualFundSubOption mutualFundSubOptionId;

    @OneToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "BANK_ID", referencedColumnName = "ID")
	private MBankName bankId;

	public Date getInvestmentDate() {
		return this.investmentDate;
	}

	public void setInvestmentDate(Date investmentDate) {
		this.investmentDate = investmentDate;
	}

	public String getFolioNumber() {
		return this.folioNumber;
	}

	public void setFolioNumber(String folioNumber) {
		this.folioNumber = folioNumber;
	}

	public String getChequeNumber() {
		return this.chequeNumber;
	}

	public void setChequeNumber(String chequeNumber) {
		this.chequeNumber = chequeNumber;
	}

	public long getInvestmentAmount() {
		return this.investmentAmount;
	}

	public void setInvestmentAmount(long investmentAmount) {
		this.investmentAmount = investmentAmount;
	}

	public String getSipEndYear() {
		return this.sipEndYear;
	}

	public void setSipEndYear(String sipEndYear) {
		this.sipEndYear = sipEndYear;
	}

	public String getSipEndMonth() {
		return this.sipEndMonth;
	}

	public void setSipEndMonth(String sipEndMonth) {
		this.sipEndMonth = sipEndMonth;
	}

	public String getSipEndDate() {
		return this.sipEndDate;
	}

	public void setSipEndDate(String sipEndDate) {
		this.sipEndDate = sipEndDate;
	}

	public String getAccountNumber() {
		return this.accountNumber;
	}

	public void setAccountNumber(String accountNumber) {
		this.accountNumber = accountNumber;
	}

	public String getMicrNumber() {
		return this.micrNumber;
	}

	public void setMicrNumber(String micrNumber) {
		this.micrNumber = micrNumber;
	}

    public BUserProfile getInvestorId() {
        return investorId;
    }

    public void setInvestorId(BUserProfile investorId) {
        this.investorId = investorId;
    }

    public MAmc getAmcId() {
        return amcId;
    }

    public void setAmcId(MAmc amcId) {
        this.amcId = amcId;
    }

    public MMutualFundOption getMutualFundOptionId() {
        return mutualFundOptionId;
    }

    public void setMutualFundOptionId(MMutualFundOption mutualFundOptionId) {
        this.mutualFundOptionId = mutualFundOptionId;
    }

    public MMutualFundSubOption getMutualFundSubOptionId() {
        return mutualFundSubOptionId;
    }

    public void setMutualFundSubOptionId(MMutualFundSubOption mutualFundSubOptionId) {
        this.mutualFundSubOptionId = mutualFundSubOptionId;
    }

    public MBankName getBankId() {
        return bankId;
    }

    public void setBankId(MBankName bankId) {
        this.bankId = bankId;
    }

    @Override
    public PropertiesHolder<TMutualFundDetail> getPropertyHolder() {
        return properties;
    }

    private static class EntityProperties implements PropertiesHolder<TMutualFundDetail> {
        private static final Set<PropertyInfo> PROPERTIES_TO_MERGE = Sets.newHashSet(
                (PropertyInfo) new PrimitiveDataTypePropertyInfo<String>(String.class, "folioNumber"),
                (PropertyInfo) new PrimitiveDataTypePropertyInfo<Long>(Long.class, "investmentAmount")
        );

        @Override
        public Set<PropertyInfo> getPropertiesInfoToBeMerged() {
            return PROPERTIES_TO_MERGE;
        }
    }
}
