package com.invest.pro.application.model.business;// default package
// Generated Sep 27, 2015 7:52:02 PM by Hibernate Tools 3.4.0.CR1

import com.google.common.collect.Sets;
import com.invest.pro.application.model.internal.PrimitiveIdAbstractEntity;
import com.invest.pro.application.property.PropertiesHolder;
import com.invest.pro.application.property.info.PrimitiveDataTypePropertyInfo;
import com.invest.pro.application.property.info.PropertyInfo;

import javax.persistence.*;
import java.util.Set;

/**
 * BAddressDetails generated by hbm2java
 */
@Entity
@Table(name = "B_ADDRESS_DETAILS")
public class BAddressDetails extends PrimitiveIdAbstractEntity<Long, BAddressDetails> {

    private static final EntityProperties properties = new EntityProperties();

    @Column(name = "ADDRESS")
	private String address;

    @Column(name = "PINCODE")
	private String pincode;

    @Column(name = "CITY")
	private String city;

    @Column(name = "DISTIC")
	private String distic;

    @Column(name = "PHONE")
	private String phone;

    @Column(name = "FAX")
	private String fax;

    @Column(name = "EMAIL")
	private String email;

    @Column(name = "ACTIVE")
	private Boolean active;

    @OneToOne
    @JoinColumn(name = "PROFILE_ID", referencedColumnName = "ID")
	private BUserProfile profileId;

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getPincode() {
		return this.pincode;
	}

	public void setPincode(String pincode) {
		this.pincode = pincode;
	}

	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public String getDistic() {
		return this.distic;
	}

	public void setDistic(String distic) {
		this.distic = distic;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getFax() {
		return this.fax;
	}

	public void setFax(String fax) {
		this.fax = fax;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public Boolean getActive() {
		return this.active;
	}

	public void setActive(Boolean active) {
		this.active = active;
	}

    public BUserProfile getProfileId() {
        return profileId;
    }

    public void setProfileId(BUserProfile profileId) {
        this.profileId = profileId;
    }

    @Override
    public PropertiesHolder<BAddressDetails> getPropertyHolder() {
        return properties;
    }

    private static class EntityProperties implements PropertiesHolder<BAddressDetails> {
        private static final Set<PropertyInfo> PROPERTIES_TO_MERGE = Sets.newHashSet(
                (PropertyInfo) new PrimitiveDataTypePropertyInfo<String>(String.class, "email"),
                (PropertyInfo) new PrimitiveDataTypePropertyInfo<String>(String.class, "pincode")
        );

        @Override
        public Set<PropertyInfo> getPropertiesInfoToBeMerged() {
            return PROPERTIES_TO_MERGE;
        }
    }

}
