package com.invest.pro.application.model.business;// default package
// Generated Sep 27, 2015 7:52:02 PM by Hibernate Tools 3.4.0.CR1

import com.google.common.collect.Sets;
import com.invest.pro.application.model.internal.PrimitiveIdAbstractEntity;
import com.invest.pro.application.property.PropertiesHolder;
import com.invest.pro.application.property.info.PrimitiveDataTypePropertyInfo;
import com.invest.pro.application.property.info.PropertyInfo;

import javax.persistence.*;
import java.util.Date;
import java.util.Set;

/**
 * BNomineeDetails generated by hbm2java
 */
@Entity
@Table(name = "B_USER_PROFILE")
public class BNomineeDetails extends PrimitiveIdAbstractEntity<Long, BNomineeDetails> {

    private static final EntityProperties properties = new EntityProperties();

    @Column(name = "FNAME")
	private String fname;

    @Column(name = "LNAME")
	private String lname;

    @Column(name = "PAN")
	private String pan;

    @Column(name = "DOB")
	private Date dob;

    @Column(name = "MOBILE")
	private String mobile;

    @Column(name = "TITLE")
	private String title;

    @Column(name = "EMAIL")
	private String email;

    @Column(name = "ACTIVE")
	private Boolean active;

    @OneToOne
    @JoinColumn(name = "PROFILE_ID", referencedColumnName = "ID")
	private BUserProfile profileId;

	public String getFname() {
		return this.fname;
	}

	public void setFname(String fname) {
		this.fname = fname;
	}

	public String getLname() {
		return this.lname;
	}

	public void setLname(String lname) {
		this.lname = lname;
	}

	public String getPan() {
		return this.pan;
	}

	public void setPan(String pan) {
		this.pan = pan;
	}

	public Date getDob() {
		return this.dob;
	}

	public void setDob(Date dob) {
		this.dob = dob;
	}

	public String getMobile() {
		return this.mobile;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public Boolean getActive() {
		return this.active;
	}

	public void setActive(Boolean active) {
		this.active = active;
	}

    public BUserProfile getProfileId() {
        return profileId;
    }

    public void setProfileId(BUserProfile profileId) {
        this.profileId = profileId;
    }

    @Override
    public PropertiesHolder<BNomineeDetails> getPropertyHolder() {
        return properties;
    }

    private static class EntityProperties implements PropertiesHolder<BNomineeDetails> {
        private static final Set<PropertyInfo> PROPERTIES_TO_MERGE = Sets.newHashSet(
                (PropertyInfo) new PrimitiveDataTypePropertyInfo<String>(String.class, "fname"),
                (PropertyInfo) new PrimitiveDataTypePropertyInfo<String>(String.class, "mobile")
        );

        @Override
        public Set<PropertyInfo> getPropertiesInfoToBeMerged() {
            return PROPERTIES_TO_MERGE;
        }
    }
}
