package com.invest.pro.application.model.business;// default package
// Generated Sep 27, 2015 7:52:02 PM by Hibernate Tools 3.4.0.CR1

import com.google.common.collect.Sets;
import com.invest.pro.application.model.internal.PrimitiveIdAbstractEntity;
import com.invest.pro.application.property.PropertiesHolder;
import com.invest.pro.application.property.info.PrimitiveDataTypePropertyInfo;
import com.invest.pro.application.property.info.PropertyInfo;

import javax.persistence.*;
import java.util.Date;
import java.util.Set;

/**
 * BUserProfile generated by hbm2java
 */
@Entity
@Table(name = "B_USER_PROFILE")
public class BUserProfile extends PrimitiveIdAbstractEntity<Long, BUserProfile> {

    private static final EntityProperties properties = new EntityProperties();


    @Column(name = "FNAME")
	private String fname;

    @Column(name = "LNAME")
	private String lname;

    @Column(name = "PAN")
	private String pan;

    @Column(name = "DOB")
	private Date dob;

    @Column(name = "MOBILE")
	private String mobile;

    @Column(name = "IS_CLIENT")
	private boolean isClient;

    @Column(name = "TITLE")
	private String title;

    @OneToOne
    @JoinColumn(name = "CLIENT_ID", referencedColumnName = "ID")
	private BUsers clientId;

    @Column(name = "ACTIVE")
    private Boolean active;


	public String getFname() {
		return this.fname;
	}

	public void setFname(String fname) {
		this.fname = fname;
	}

	public String getLname() {
		return this.lname;
	}

	public void setLname(String lname) {
		this.lname = lname;
	}

	public String getPan() {
		return this.pan;
	}

	public void setPan(String pan) {
		this.pan = pan;
	}

	public Date getDob() {
		return this.dob;
	}

	public void setDob(Date dob) {
		this.dob = dob;
	}

	public String getMobile() {
		return this.mobile;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	public boolean isIsClient() {
		return this.isClient;
	}

	public void setIsClient(boolean isClient) {
		this.isClient = isClient;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public Boolean getActive() {
		return this.active;
	}

	public void setActive(Boolean active) {
		this.active = active;
	}

    public BUsers getClientId() {
        return clientId;
    }

    public void setClientId(BUsers clientId) {
        this.clientId = clientId;
    }

    @Override
    public PropertiesHolder<BUserProfile> getPropertyHolder() {
        return properties;
    }

    private static class EntityProperties implements PropertiesHolder<BUserProfile> {
        private static final Set<PropertyInfo> PROPERTIES_TO_MERGE = Sets.newHashSet(
                (PropertyInfo) new PrimitiveDataTypePropertyInfo<String>(String.class, "fname"),
                (PropertyInfo) new PrimitiveDataTypePropertyInfo<String>(String.class, "clientId"),
                (PropertyInfo) new PrimitiveDataTypePropertyInfo<Boolean>(Boolean.class, "isClient"),
                (PropertyInfo) new PrimitiveDataTypePropertyInfo<Date>(Date.class, "pan")
        );

        @Override
        public Set<PropertyInfo> getPropertiesInfoToBeMerged() {
            return PROPERTIES_TO_MERGE;
        }
    }
}