package com.invest.pro.application.model.business;// default package
// Generated Sep 27, 2015 7:52:02 PM by Hibernate Tools 3.4.0.CR1

import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.google.common.collect.Sets;
import com.invest.pro.application.jackson.PasswordSerializer;
import com.invest.pro.application.model.internal.PrimitiveIdAbstractEntity;
import com.invest.pro.application.property.PropertiesHolder;
import com.invest.pro.application.property.info.PrimitiveDataTypePropertyInfo;
import com.invest.pro.application.property.info.PropertyInfo;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;
import java.util.Set;

/**
 * BUsers generated by hbm2java
 */
@Entity
@Table(name = "B_USERS")
public class BUsers extends PrimitiveIdAbstractEntity<Long, BUsers> {

    private static final EntityProperties properties = new EntityProperties();


    @Column(name = "USERNAME")
	private String username;

    @JsonSerialize(using = PasswordSerializer.class)
    @Column(name = "PASSWORD")
	private String password;

    @Column(name = "ACTIVE")
	private Boolean active;

	public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public Boolean getActive() {
        return active;
    }

    public void setActive(Boolean active) {
        this.active = active;
    }

    @Override
    public PropertiesHolder<BUsers> getPropertyHolder() {
        return properties;
    }

    private static class EntityProperties implements PropertiesHolder<BUsers> {
        private static final Set<PropertyInfo> PROPERTIES_TO_MERGE = Sets.newHashSet(
                (PropertyInfo) new PrimitiveDataTypePropertyInfo<String>(String.class, "password"),
                (PropertyInfo) new PrimitiveDataTypePropertyInfo<String>(String.class, "username")
                );

        @Override
        public Set<PropertyInfo> getPropertiesInfoToBeMerged() {
            return PROPERTIES_TO_MERGE;
        }
    }
    }
